### PR TITLE
Faction skill trees and AT-XT

### PR DESCRIPTION
**Pull request by asyncliz**
Test cases

- Character with rank 10 before upgrade: should log in with Second Lieutenant and +2 Loyalty
- Character with rank 15 before upgrade: should log in with Colonel skill (and previous skills) with +15 Loyalty
- Positive and negative faction before upgrade should translate to positive and negative faction experience after upgrade
- Neutral characters with 0 faction before upgrade should log in without any faction experience or faction skills
- Character with rank 15 after upgrade and enough faction for rank 16 should not be able to accept a promotion
- Character with faction skills should not be able to train to other characters or surrender them
- Resigning faction should drop all faction skills and Loyalty modifiers gained from them
- Character below rank 11 (Lieutenant) should not be able to buy bases
- Rank 11, 12, 13, and 14 each unlock the next tier base to buy
- Rank 12 (Captain) should be able to jam uplink terminals
- Rank 14 (Lt Colonel) should be able to slice security terminals
- Loyalty modifier should increase faction gain AND loss by 1% per point
- Loyalty should NOT affect spending faction, such as with promotions, buying items, or delegating (sending and receiving)
- Player should not be able to gain or lose faction experience outside of their faction caps. -5000 is the lower cap. Rank * 20 (or 1000, whichever is greater) is the upper cap.
- Many faction items (factionPerkData.lua) have rank requirements. If there is a rank requirement, it should not be possible to buy the item.

### CODE REVIEW

**Comment by TrigsC** [comment]
I was major pre patch. I bought a ton of bases. faction did not increase or decrease. I then dropped faction at recruiter. I had banked up rebel faction more than 1000 and retained all 89500. I rejoined rebel and as I was ranking again I noticed the skill sheet said 1000 but the character sheet said 89500. I was able to rank all the way back to Col without needing to get more faction from frog. The 89500 was still banked and allowing me to rank.

If you die your faction points decrease just dropping faction and buying stuff does not decrease FP

**Comment by TrigsC** [comment]
Player faction pet attacks another player faction pet is crashing server as ghostattacker is not being checked for null before. Do you want to add this commit to yours also?

https://github.com/swgintended/Core3/blob/unstable/MMOCoreORB/src/server/zone/managers/combat/CombatManager.cpp#L272

`if (ghostAttacker != nullptr && defenderCreature->isAiAgent() && defenderCreature->getFaction() != attacker->getFaction() && (defenderCreature->getFaction() == Factions::FACTIONREBEL || defenderCreature->getFaction() == Factions::FACTIONIMPERIAL) && !areInDuel(attacker, defenderCreature))
                        ghostAttacker->updateLastPvpCombatActionTimestamp(false, false, true, false);`

**Comment by TrigsC** [comment]
AT-XT needs to have the same message as AT-ST for allowed pets called. Right now you can call 3 AT-XT's at the same time.
Verbiage: `You already have the maximum number of pets of this type that you can call.`

https://github.com/swgintended/Core3/blob/unstable/MMOCoreORB/src/server/zone/objects/intangible/PetControlDeviceImplementation.cpp#L207

Below does not work but something like this maybe to fix it?
`if (++currentlySpawned >= maxPets || (activePetTemplate->getTemplateName() == "at_st" && callingPetTemplate->getTemplateName() == "at_st") || (activePetTemplate->getTemplateName() == "at_xt" && callingPetTemplate->getTemplateName() == "at_xt")) {`

**Comment by asyncliz** [comment]
Fixed all three of the bugs listed:

- Faction points are removed when purchasing items and accepting promotions from the recruiter.
- AT-XTs are limited to 1 call for player. Players may call 2 additional NPC faction pets in addition to the AT-XT.
- Fixed crash when engaging players with faction pets.

**Review by TrigsC — CHANGES_REQUESTED** [review]
I would rather not include all these changes to the combat manager right now. This will just hold up the release. I know you are confident in it however just too much going on not to do a very thorough test.

**Comment by asyncliz** [comment]
Updated

**Comment by TrigsC** [comment]
Good to go!

**Pull request merged**
